num1 = float(input("digite o primeiro número"))
num2 = float(input("digite o segundo número"))
num3 = float(input("digite o terceiro número"))
maior = max(num1, num2, num3)
menor = min(num1, num2, num3)
print("O maior número é: {}".format(maior))
print("O menor número é: {}".format(menor))